# Generated by Django 5.1.4 on 2025-02-25 14:48

import apps.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.account.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Resume',
            new_name='resume',
        ),
    ]
